function llr = demap_llr_16QAM(y,SNR)
%QAM_16_LLR 此处显示有关此函数的摘要
%input为接收端收到的调制符号,SNR为信噪比
i_length=length(y);
LLR_length=i_length*4;
%P=zeros(1,i_length);
%ImP=zeros(1,i_length);

llr=zeros(LLR_length,1);

delta2=1/(10^(SNR/10));

% for k=1:i_length
%     P(k)=real(input(k));
%     ImP(k)=imag(input(k));    
%     
%     LLR(4*(k-1)+1)=log((exp(-(P(k)-delta/sqrt(10)).^2)/(2*delta2))+...
%                        (exp(-(P(k)-3*delta/sqrt(10)).^2)/(2*delta2)))...
%                   -log((exp(-(P(k)-(-1)*delta/sqrt(10)).^2)/(2*delta2))+...
%                        (exp(-(P(k)-(-3)*delta/sqrt(10)).^2)/(2*delta2)));
%     
%     LLR(4*(k-1)+3)=log((exp(-(P(k)-delta/sqrt(10)).^2)/(2*delta2))+...
%                        (exp(-(P(k)-(-1)*delta/sqrt(10)).^2)/(2*delta2)))...
%                   -log((exp(-(P(k)-3*delta/sqrt(10)).^2)/(2*delta2))+...
%                        (exp(-(P(k)-(-3)*delta/sqrt(10)).^2)/(2*delta2)));
%                    
%     LLR(4*(k-1)+2)=log((exp(-(ImP(k)-delta/sqrt(10)).^2)/(2*delta2))+...
%                        (exp(-(ImP(k)-3*delta/sqrt(10)).^2)/(2*delta2)))...
%                   -log((exp(-(ImP(k)-(-1)*delta/sqrt(10)).^2)/(2*delta2))+...
%                        (exp(-(ImP(k)-(-3)*delta/sqrt(10)).^2)/(2*delta2)));
%     
%     LLR(4*(k-1)+4)=log((exp(-(ImP(k)-delta/sqrt(10)).^2)/(2*delta2))+...
%                        (exp(-(ImP(k)-(-1)*delta/sqrt(10)).^2)/(2*delta2)))...
%                   -log((exp(-(ImP(k)-3*delta/sqrt(10)).^2)/(2*delta2))+...
%                        (exp(-(ImP(k)-(-3)*delta/sqrt(10)).^2)/(2*delta2)));
% end
%.......................................................................................................


%%边界判决

%LLR(1:4:end)=real(input(1:1:end));
%LLR(3:4:end)=2/sqrt(10)-abs(real(input(1:1:end)));

%LLR(2:4:end)=imag(input(1:1:end));
%LLR(4:4:end)=2/sqrt(10)-abs(imag(input(1:1:end)));        
%........................................................................................................


% LLR(1:4:end)=1/(2*delta2)*((real(input(1:1:end))>(-2/sqrt(10))).*(real(input(1:1:end))+1/sqrt(10)).^2 ...
%                           +(real(input(1:1:end))<=(-2/sqrt(10))).*(real(input(1:1:end))+3/sqrt(10)).^2)...   
%             -1/(2*delta2)*((real(input(1:1:end))<(2/sqrt(10))).*(real(input(1:1:end))-1/sqrt(10)).^2 ...
%                           +(real(input(1:1:end))>=(2/sqrt(10))).*(real(input(1:1:end))-3/sqrt(10)).^2);
% LLR(3:4:end)=1/(2*delta2)*((real(input(1:1:end))>0).*(real(input(1:1:end))-3/sqrt(10)).^2 ...
%                           +(real(input(1:1:end))<=0).*(real(input(1:1:end))+3/sqrt(10)).^2)...   
%             -1/(2*delta2)*((real(input(1:1:end))>0).*(real(input(1:1:end))-1/sqrt(10)).^2 ...
%                           +(real(input(1:1:end))<=0).*(real(input(1:1:end))+1/sqrt(10)).^2);
% 
% LLR(2:4:end)=1/(2*delta2)*((imag(input(1:1:end))>(-2/sqrt(10))).*(imag(input(1:1:end))+1/sqrt(10)).^2 ...
%                           +(imag(input(1:1:end))<=(-2/sqrt(10))).*(imag(input(1:1:end))+3/sqrt(10)).^2)...   
%             -1/(2*delta2)*((imag(input(1:1:end))<=(2/sqrt(10))).*(imag(input(1:1:end))-1/sqrt(10)).^2 ...
%                           +(imag(input(1:1:end))>(2/sqrt(10))).*(imag(input(1:1:end))-3/sqrt(10)).^2);
% LLR(4:4:end)=1/(2*delta2)*((imag(input(1:1:end))>0).*(imag(input(1:1:end))-3/sqrt(10)).^2 ...
%                           +(imag(input(1:1:end))<=0).*(imag(input(1:1:end))+3/sqrt(10)).^2)...   
%             -1/(2*delta2)*((imag(input(1:1:end))>0).*(imag(input(1:1:end))-1/sqrt(10)).^2 ...
%                           +(imag(input(1:1:end))<=0).*(imag(input(1:1:end))+1/sqrt(10)).^2);

llr(1:4:end)=1/(2*delta2)*...
                          (min(((real(y(1:1:end))-(-1)/sqrt(10)).^2),((real(y(1:1:end))-(-3)/sqrt(10)).^2))...
                         -(min(((real(y(1:1:end))-1/sqrt(10)).^2),((real(y(1:1:end))-3/sqrt(10)).^2))));
llr(3:4:end)=1/(2*delta2)*...
                          (min(((real(y(1:1:end))-(-3)/sqrt(10)).^2),((real(y(1:1:end))-3/sqrt(10)).^2))...
                         -(min(((real(y(1:1:end))-(-1)/sqrt(10)).^2),((real(y(1:1:end))-1/sqrt(10)).^2))));

llr(2:4:end)=1/(2*delta2)*...
                          (min(((imag(y(1:1:end))-(-1)/sqrt(10)).^2),((imag(y(1:1:end))-(-3)/sqrt(10)).^2))...
                         -(min(((imag(y(1:1:end))-1/sqrt(10)).^2),((imag(y(1:1:end))-3/sqrt(10)).^2))));
llr(4:4:end)=1/(2*delta2)*...
                          (min(((imag(y(1:1:end))-(-3)/sqrt(10)).^2),((imag(y(1:1:end))-3/sqrt(10)).^2))...
                         -(min(((imag(y(1:1:end))-(-1)/sqrt(10)).^2),((imag(y(1:1:end))-1/sqrt(10)).^2))));                   



end

